# vim: set filetype=dockerfile:

FROM ubuntu:16.04

RUN apt-get install -y python-pip
RUN pip install --upgrade pip

# Install CPU only version of PyTorch
RUN test -z "$CUDA_VERSION" && \
	pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl || true
# Install CUDA version of PyTorch
RUN test -n "$CUDA_VERSION" && \
	bash -c 'pip install "http://download.pytorch.org/whl/cu${CUDA_VERSION:0:1}${CUDA_VERSION:2:1}/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl"' || true
RUN pip install torchvision
